
name: phx dockerfile push
on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push phx image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: $DOCKER_USER
          password: $DOCKER_PASS
          repository: buenolucas/phx
          tag_with_ref: true
          tags: latest
